language: cpp
os:
- linux
- osx
compiler:
- clang
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - george-edison55-precise-backports #for cmake3
    packages:
    - g++-4.8
    - clang-3.7
    - cmake
    - cmake-data
install:
    - if [ "`echo $CXX`" == "g++" ]     && [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX=g++-4.8; fi
    - if [ "`echo $CXX`" == "clang++" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX=clang++-3.7; fi
matrix:
  exclude:
  - os: osx
    compiler: gcc
script:
    - mkdir build
    - cd build
    - cmake .. && make && make package
    - cd ..
before_deploy:
    - export RELEASE_FILE=$(ls build/bcalm-binaries-*.tar.gz)
    - ls
    - ls build
    - echo "Deploying $RELEASE_FILE to GitHub"
deploy:
  provider: releases
  api_key:
    secure: KW6qAyrtX1fyCpZEjttW4YaKRGFvioqYBoN3mvlGJeYJqTFvuPbQ4PMA+ueQWvQFImhF74C/WQjnw0uUgRpBUV5mQZOFqA0QIGJNaIkL/dSqs7N9YI97VX3TH/GxPsLpW1KfQPF0DkCJ8pobWEz5k3Itl8woSXcX2HskxtQNKA0=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    repo: GATB/bcalm
    tags: true

